#!/bin/bash

# create config file

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
polybar_config_file="$DIR/config"

echo '; THIS FILE IS AUTOGENERATED' > $polybar_config_file 

for config_file in $(ls $DIR/*.config); do
    echo "include-file = $config_file" >> $polybar_config_file
done

# kill running polybars

killall -q polybar

# set ethernet device

NETDEV=$(ip a | grep mtu | grep group | cut -d: -f2 | tr -d ' ' | grep -v "vbox\|wlp\|wwp\|lo")
# run an instance of polybar per screen

for d in $(xrandr --listmonitors | awk '{print $4}'); 
do 
  MONITOR=$d NETDEV=$NETDEV polybar main &
done
