#!/bin/bash

# create config file

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
polybar_config_file="$DIR/config"

echo '; THIS FILE IS AUTOGENERATED' > $polybar_config_file 

for config_file in $(ls $DIR/*.config); do
    echo "include-file = $config_file" >> $polybar_config_file
done


# kill running polybars
killall -q polybar

# launch polybar

polybar main &
